const { chromium, devices } = require('playwright');
(async () => {
  const browser = await chromium.launch({ proxy: process.env.HTTPS_PROXY ? { server: process.env.HTTPS_PROXY } : undefined, args: ['--ignore-certificate-errors'] });
  const ctx = await browser.newContext({ ...devices['iPhone 13'], ignoreHTTPSErrors: true });
  const page = await ctx.newPage();
  const errs = []; page.on('pageerror', e => errs.push(e.message)); page.on('console', m => { if (m.type() === 'error') errs.push(m.text().slice(0, 120)); });
  await page.goto('https://ferienwohnung-see-brandenburg.de/', { waitUntil: 'networkidle', timeout: 120000 });
  await page.waitForTimeout(1500);
  await page.screenshot({ path: 'qa/hero-390.png', clip: { x: 0, y: 0, width: 390, height: 844 } });
  const m = (sel, n = 3) => Array.from(document.querySelectorAll(sel)).slice(0, n).map(e => { const r = e.getBoundingClientRect(); return [e.textContent.trim().slice(0, 22), Math.round(r.width), Math.round(r.height)]; });
  await page.click('#mobile-menu-btn'); await page.waitForTimeout(600);
  const open = await page.evaluate(() => { const el = document.getElementById('mobile-menu'); return { hidden: el.getAttribute('aria-hidden'), x: Math.round(el.getBoundingClientRect().x), expanded: document.getElementById('mobile-menu-btn').getAttribute('aria-expanded') }; });
  await page.screenshot({ path: 'qa/menu-390.png', clip: { x: 0, y: 0, width: 390, height: 844 } });
  await page.click('#mobile-menu-close'); await page.waitForTimeout(600);
  const closed = await page.evaluate(() => { const el = document.getElementById('mobile-menu'); return { hidden: el.getAttribute('aria-hidden'), x: Math.round(el.getBoundingClientRect().x) }; });
  console.log('menu', JSON.stringify({ open, closed }));
  const t = await page.evaluate((src) => { const m = eval(src); return { footerLinks: m('footer a.inline-block', 4), footerBtn: m('footer button'), subfooter: m('footer .border-t a'), eyebrowPx: getComputedStyle(document.querySelector('.eyebrow')).fontSize, wordmarkPx: getComputedStyle(document.querySelector('footer span.uppercase')).fontSize, convert: m('a.convert', 4), checkbox: m('#privacy_consent'), summary: m('summary'), heroSrc: document.querySelector('[data-hero] img').currentSrc.split('/').pop(), cardSrcs: Array.from(document.querySelectorAll('article img')).map(i => i.currentSrc.split('/').pop()) }; }, m.toString());
  console.log('home', JSON.stringify(t));
  await page.goto('https://ferienwohnung-see-brandenburg.de/faq', { waitUntil: 'networkidle', timeout: 120000 });
  console.log('faq', JSON.stringify(await page.evaluate((src) => { const m = eval(src); return { summary: m('summary'), chips: m('a.inline-flex.rounded-full') }; }, m.toString())));
  await page.goto('https://ferienwohnung-see-brandenburg.de/kontakt', { waitUntil: 'networkidle', timeout: 120000 });
  console.log('kontakt', JSON.stringify(await page.evaluate((src) => { const m = eval(src); return { convert: m('a.convert.inline-flex'), cc: m('.cc-btn') }; }, m.toString())));
  console.log('console errors:', JSON.stringify(errs));
  const dctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, ignoreHTTPSErrors: true }); const dp = await dctx.newPage();
  await dp.goto('https://ferienwohnung-see-brandenburg.de/', { waitUntil: 'networkidle', timeout: 120000 });
  await dp.waitForTimeout(1500);
  console.log('nav', JSON.stringify(await dp.evaluate(() => Array.from(document.querySelectorAll('#main-nav .nav-link')).map(e => { const r = e.getBoundingClientRect(); return [e.textContent.trim(), Math.round(r.width), Math.round(r.height)]; }))));
  await dp.screenshot({ path: 'qa/home-1440.png', clip: { x: 0, y: 0, width: 1440, height: 900 } });
  await browser.close();
})().catch(e => { console.error('FAILED', e.message); process.exit(1); });
